{
    "openapi": "3.0.0",
    "info": {
        "title": "API para o Departamento de Polícia",
        "description": "Essa é uma API de um departamento de poícia que permite o gerenciamento de agentes e casos policiais fictícios, com validações, tratamento de erros e dados armazenados em memória (utilizando arrays).",
        "version": "1.0.0",
        "contact": {
            "name": "Helena Edim",
            "email": "edimhelenaguimaraes@gmail.com"
        }
    },
    "servers": [
        {
            "url": "http://localhost:3000",
            "description": "Servidor local (Node/Express)"
        }
    ],
    "paths": {
        "/casos": {
            "get": {
                "summary": "Retorna todos os casos",
                "description": "Essa rota será reponsável por retornar todos os casos",
                "tags": [
                    "Casos"
                ],
                "responses": {
                    "200": {
                        "description": "Retorna todos os casos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "example": [
                                        {
                                            "id": "1",
                                            "titulo": "Caso 1",
                                            "descricao": "Descrição do caso 1",
                                            "status": "aberto",
                                            "agente_id": "1"
                                        },
                                        {
                                            "id": "2",
                                            "titulo": "Caso 2",
                                            "descricao": "Descrição do caso 2",
                                            "status": "solucionado",
                                            "agente_id": "2"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Cria um caso",
                "description": "Essa rota será reponsável por criar um caso",
                "tags": [
                    "Casos"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Caso"
                            }
                        },
                        "examples": {
                            "caso": {
                                "value": {
                                    "titulo": "Caso 1",
                                    "descricao": "Descrição do caso 1",
                                    "status": "aberto",
                                    "agente_id": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Caso criado com sucesso"
                    },
                    "400": {
                        "description": "Dados incorretos ou incompletos"
                    },
                    "404": {
                        "description": "Id do agente não encontrado"
                    }
                }
            }
        },
        "/casos/{id}": {
            "get": {
                "summary": "Retorna o caso com o determinado ID",
                "description": "Essa rota será reponsável por retornar um caso específico",
                "tags": [
                    "Casos"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Caso retornado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "id": "1",
                                        "titulo": "Caso 1",
                                        "descricao": "Descrição do caso 1",
                                        "status": "aberto",
                                        "agente_id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Caso não encontrado"
                    }
                }
            },
            "put": {
                "summary": "Atualiza completamente um caso de acordo com o id passado na rota",
                "description": "Essa rota será reponsável por atualizar completamente um caso de acordo com o id passado na rota",
                "tags": [
                    "Casos"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Caso"
                            }
                        },
                        "examples": {
                            "caso": {
                                "value": {
                                    "titulo": "Caso 1 atualizado",
                                    "descricao": "Descrição do caso 1 atualizada",
                                    "status": "solucionado",
                                    "agente_id": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Caso atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "titulo": "Caso 1 atualizado",
                                        "descricao": "Descrição do caso 1 atualizada",
                                        "status": "solucionado",
                                        "agente_id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Caso ou agente não encontrado"
                    },
                    "400": {
                        "description": "Dados incorretos ou incompletos"
                    }
                }
            },
            "patch": {
                "summary": "Atualiza parcialmente um caso",
                "description": "Essa rota permite atualizar apenas alguns campos de um caso, de acordo com o ID passado na URL.",
                "tags": [
                    "Casos"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "titulo": {
                                        "type": "string"
                                    },
                                    "descricao": {
                                        "type": "string"
                                    },
                                    "status": {
                                        "type": "string",
                                        "enum": [
                                            "aberto",
                                            "solucionado"
                                        ]
                                    },
                                    "agente_id": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "atualizar_status": {
                                    "summary": "Atualizar apenas o status",
                                    "value": {
                                        "status": "solucionado"
                                    }
                                },
                                "atualizar_titulo_e_descricao": {
                                    "summary": "Atualizar título e descrição",
                                    "value": {
                                        "titulo": "Novo título",
                                        "descricao": "Nova descrição do caso"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Caso atualizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Caso"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Requisição inválida"
                    },
                    "404": {
                        "description": "Caso ou agente não encontrado"
                    }
                }
            },
            "delete": {
                "summary": "Deleta caso",
                "description": "Essa rota permite deletar um caso de acordo com o id passado na URL",
                "tags": [
                    "Casos"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Caso não encontrado"
                    },
                    "204": {
                        "description": "Caso deletado com sucesso"
                    }
                }
            }
        },
        "/docs-swagger": {
            "get": {
                "summary": "Retorna a documentação da API",
                "description": "Essa rota será reponsável por retornar a documentação em json da API feita pelo swagger",
                "tags": [
                    "Documentação"
                ],
                "responses": {
                    "200": {
                        "description": "Retorna a documentação",
                        "content": {
                            "text/json": {}
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Caso": {
                "type": "object",
                "required": [
                    "titulo",
                    "descricao",
                    "status",
                    "agente_id"
                ],
                "properties": {
                    "titulo": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string",
                        "enum": [
                            "aberto",
                            "solucionado"
                        ]
                    },
                    "agente_id": {
                        "type": "string",
                        "format": "uuid"
                    }
                }
            }
        }
    }
}